# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170501_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='personal',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
